name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 -t jmcglock/from-code-to-cloud:latest .
      - name: Publish Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker tag jmcglock/from-code-to-cloud:latest jmcglock/from-code-to-cloud:$(date +%Y%m%d.%H%M)
          docker push jmcglock/from-code-to-cloud:latest
          docker push jmcglock/from-code-to-cloud:$(date +%Y%m%d.%H%M)